language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
services:
  - mongodb
sudo: false
install:
  - cpanm -nq --installdeps --with-develop .
before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Makefile.PL
  - make
  - cover -test
after_success:
  - cover -report codecov
