#!/usr/bin/env perl
use strict;
use warnings;
use App::GAWM;

App::GAWM->run;

=head1 OVERVIEW

For help with App::GAWM, run "gawm help"

=cut

__END__

perl -I lib/ script/gawm

perl -I lib/ t/02-init.t

perl -I lib/ script/gawm init
perl -I lib/ script/gawm init check
perl -I lib/ script/gawm init drop
#mongorestore t/Atha --db gawm
perl -I lib/ script/gawm init restore --dir t/Atha
perl -I lib/ script/gawm init dump --dir .

perl -I lib/ script/gawm init drop
perl -I lib/ script/gawm gen --dir t/S288c
perl -I lib/ script/gawm position --file t/spo11_hot.pos.txt --tag spo11 --type hot

perl -I lib/ script/gawm init drop
perl -I lib/ script/gawm gen --dir t/S288c
perl -I lib/ script/gawm gcwave
perl -I lib/ script/gawm swcv

perl -I lib/ script/gawm init drop
perl -I lib/ script/gawm gen --dir t/S288c
perl -I lib/ script/gawm gcwave
perl -I lib/ script/gawm count insert --file t/spo11_hot.pos.txt
perl -I lib/ script/gawm count count

perl -I lib/ script/gawm init drop
perl -I lib/ script/gawm gen --dir t/S288c
perl -I lib/ script/gawm position --file t/spo11_hot.pos.txt --tag spo11 --type hot
perl -I lib/ script/gawm gcwave
perl -I lib/ script/gawm count insert --file t/spo11_hot.pos.txt
perl -I lib/ script/gawm count count
perl -I lib/ script/gawm swcv
perl -I lib/ script/gawm stat --index --chart --by tt --replace POS=HotSpots
