#!/usr/bin/env perl
use strict;
use warnings;
use App::GAWM;

App::GAWM->run;

=head1 OVERVIEW

For help with App::GAWM, run "gawm help"

=cut

__END__

perl -I lib/ script/gawm

perl -I lib/ t/02-init.t

perl -I lib/ script/gawm init
